services:

  db-test:
    image: postgres:17.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - '5432:5432'
    env_file: .db.test.env

  cache-test:
    image: redis:8.0-M02-alpine
    restart: always
    ports:
      - '6379:6379'

  rabbitmq-test:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"