"""del-token-in-UserProfile

Revision ID: af82164cf0b1
Revises: 701cfc661256
Create Date: 2025-01-27 02:06:27.058737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af82164cf0b1'
down_revision: Union[str, None] = '701cfc661256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserProfile', 'google_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('google_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
